INSERT INTO users(username, profile_photo_url, bio,email) VALUES 
('Ahammed Shorif','https://devforum-uploads.s3.dualstack.us-east-2.amazonaws.com/uploads/original/4X/0/3/1/031b0eafd9e889b7ed5e6aee6c63fb1b1b157e82.jpeg',' CSE  || IIUC','ahammedshorif@gmial.com'),
('Shakil Ahammed' , '/klsadf893724.png' , 'soon to be updated','admin@yahoo.com'),
('Tanvir Ahmed' , 'https://pbs.twimg.com/profile_images/1465003815820693506/gbTJoe66_400x400.jpg' ,'sitakunda || IIUC','tanvir@gmail.com'),
('Rakib Mozumder' , 'https://vader.news/__export/1612817390103/sites/gadgets/img/2021/02/08/ian_somerhalder_vampires.jpg_246448593.jpg' , '____','deepak@24sevenindia.com'),
('Samiul Hasan', '/sdfvsdf.png', 'codeforces Messege || IIUC','sami@gmail.com'),
('Saif', '/sdfvsdf.png', 'CR  || IIUC','saif@gmail.com'),
('Tarakul Islam' , '/yisadf324.png' , 'CEO of IMO  || IIUC','emo@gmail.com'),
('Ovi' , '/fduiahj43.png' , 'dew || iiuc','ovi@gmail.com' ),
('Panda' , '/adaskjnas.jpg','Panda lover || iiuc','panda686@gmail.com'),
('Siam','/acdsccsdc.png', 'living life my way || iiuc','siam07@yahoo.com'),
('ADB','https://shorturl.at/cpAU6',' CSE  || IIUC','adb@gmial.com'),
('Pamel' , 'https://shorturl.at/cpAU6' , 'Nothing to say ','pamel@yahoo.com'),
('Shawon' , 'https://shorturl.at/cpAU6' ,' Topper 2 || IIUC','shawo@gmail.com'),
('Asad' , 'https://shorturl.at/cpAU6' , 'PUBG || Efootball','asadk@24sevenindia.com'),
('Samiul Islam', 'https://shorturl.at/cpAU6g', ' Good boy Rafi || IIUC','samiul@gmail.com'),
('Abrar', 'https://shorturl.at/cpAU6', ' Discord  || IIUC','abrar@gmail.com'),
('Emo' , 'https://shorturl.at/cpAU6' , 'CEO of IMO || top level coder  || IIUC','emo.@gmail.com'),
('Rahi' , 'https://shorturl.at/cpAU6' , 'Topper || CP || iiuc','rahi@gmail.com' ),
('Raj' , 'https://shorturl.at/cpAU6','video creator || iiuc','raj686@gmail.com'),
('Jamil','https://shorturl.at/cpAU6', 'Laksam || iiuc','jamil07@yahoo.com');